import BlessLevelConfig from "./BlessLevelConfig";
import BlessTypeConfig from "./BlessTypeConfig";
import BossRushConfig from "./BossRushConfig";
import BuildingLevelConfig from "./BuildingLevelConfig";
import CaveRushConfig from "./CaveRushConfig";
import CollectionConfig from "./CollectionConfig";
import ConstConfig from "./ConstConfig";
import DwarvenKingConfig from "./DwarvenKingConfig";
import EnemyConfig from "./EnemyConfig";
import ExtraRewardConfig from "./ExtraRewardConfig";
import GearConfig from "./GearConfig";
import GearLevelConfig from "./GearLevelConfig";
import GoldRushConfig from "./GoldRushConfig";
import GuideConfig from "./GuideConfig";
import GuideTextConfig from "./GuideTextConfig";
import HeroConfig from "./HeroConfig";
import HeroLevelExpConfig from "./HeroLevelExpConfig";
import LegionHeroConfig from "./LegionHeroConfig";
import LegionRandConfig from "./LegionRandConfig";
import LegionRushConfig from "./LegionRushConfig";
import LegionWaveConfig from "./LegionWaveConfig";
import LevelConfig from "./LevelConfig";
import MailboxConfig from "./MailboxConfig";
import MasteryConfig from "./MasteryConfig";
import MineConfig from "./MineConfig";
import MineResearchConfig from "./MineResearchConfig";
import MineRewardGearConfig from "./MineRewardGearConfig";
import PartnerConfig from "./PartnerConfig";
import PartnerLevelConfig from "./PartnerLevelConfig";
import PassConfig from "./PassConfig";
import PlunderHeroConfig from "./PlunderHeroConfig";
import PlunderLevelConfig from "./PlunderLevelConfig";
import PlunderQuestConfig from "./PlunderQuestConfig";
import PropLevelConfig from "./PropLevelConfig";
import QuestConfig from "./QuestConfig";
import RelicConfig from "./RelicConfig";
import RelicLevelConfig from "./RelicLevelConfig";
import RingConfig from "./RingConfig";
import RingLevelConfig from "./RingLevelConfig";
import RingQualityLevelConfig from "./RingQualityLevelConfig";
import RouletteConfig from "./RouletteConfig";
import SevenChallengeConfig from "./SevenChallengeConfig";
import SevenLoginConfig from "./SevenLoginConfig";
import ShopConfig from "./ShopConfig";
import SkillConfig from "./SkillConfig";
import SkillLevelConfig from "./SkillLevelConfig";
import SummonExtraConfig from "./SummonExtraConfig";
import SummonWidgetConfig from "./SummonWidgetConfig";
import TraitCombConfig from "./TraitCombConfig";
import TraitConfig from "./TraitConfig";
import TreasureConfig from "./TreasureConfig";
import TreasureCostConfig from "./TreasureCostConfig";
import TreasureLevelConfig from "./TreasureLevelConfig";
export default class Config {
    public static blessLevel: BlessLevelConfig = new BlessLevelConfig();
    public static blessType: BlessTypeConfig = new BlessTypeConfig();
    public static bossRush: BossRushConfig = new BossRushConfig();
    public static buildingLevel: BuildingLevelConfig = new BuildingLevelConfig();
    public static caveRush: CaveRushConfig = new CaveRushConfig();
    public static collection: CollectionConfig = new CollectionConfig();
    public static const: ConstConfig = new ConstConfig();
    public static dwarvenKing: DwarvenKingConfig = new DwarvenKingConfig();
    public static enemy: EnemyConfig = new EnemyConfig();
    public static extraReward: ExtraRewardConfig = new ExtraRewardConfig();
    public static gear: GearConfig = new GearConfig();
    public static gearLevel: GearLevelConfig = new GearLevelConfig();
    public static goldRush: GoldRushConfig = new GoldRushConfig();
    public static guide: GuideConfig = new GuideConfig();
    public static guideText: GuideTextConfig = new GuideTextConfig();
    public static hero: HeroConfig = new HeroConfig();
    public static heroLevelExp: HeroLevelExpConfig = new HeroLevelExpConfig();
    public static legionHero: LegionHeroConfig = new LegionHeroConfig();
    public static legionRand: LegionRandConfig = new LegionRandConfig();
    public static legionRush: LegionRushConfig = new LegionRushConfig();
    public static legionWave: LegionWaveConfig = new LegionWaveConfig();
    public static level: LevelConfig = new LevelConfig();
    public static mailbox: MailboxConfig = new MailboxConfig();
    public static mastery: MasteryConfig = new MasteryConfig();
    public static mine: MineConfig = new MineConfig();
    public static mineResearch: MineResearchConfig = new MineResearchConfig();
    public static mineRewardGear: MineRewardGearConfig = new MineRewardGearConfig();
    public static partner: PartnerConfig = new PartnerConfig();
    public static partnerLevel: PartnerLevelConfig = new PartnerLevelConfig();
    public static pass: PassConfig = new PassConfig();
    public static plunderHero: PlunderHeroConfig = new PlunderHeroConfig();
    public static plunderLevel: PlunderLevelConfig = new PlunderLevelConfig();
    public static plunderQuest: PlunderQuestConfig = new PlunderQuestConfig();
    public static propLevel: PropLevelConfig = new PropLevelConfig();
    public static quest: QuestConfig = new QuestConfig();
    public static relic: RelicConfig = new RelicConfig();
    public static relicLevel: RelicLevelConfig = new RelicLevelConfig();
    public static ring: RingConfig = new RingConfig();
    public static ringLevel: RingLevelConfig = new RingLevelConfig();
    public static ringQualityLevel: RingQualityLevelConfig = new RingQualityLevelConfig();
    public static roulette: RouletteConfig = new RouletteConfig();
    public static sevenChallenge: SevenChallengeConfig = new SevenChallengeConfig();
    public static sevenLogin: SevenLoginConfig = new SevenLoginConfig();
    public static shop: ShopConfig = new ShopConfig();
    public static skill: SkillConfig = new SkillConfig();
    public static skillLevel: SkillLevelConfig = new SkillLevelConfig();
    public static summonExtra: SummonExtraConfig = new SummonExtraConfig();
    public static summonWidget: SummonWidgetConfig = new SummonWidgetConfig();
    public static trait: TraitConfig = new TraitConfig();
    public static traitComb: TraitCombConfig = new TraitCombConfig();
    public static treasure: TreasureConfig = new TreasureConfig();
    public static treasureCost: TreasureCostConfig = new TreasureCostConfig();
    public static treasureLevel: TreasureLevelConfig = new TreasureLevelConfig();
    static async load() {
        let all = [];
        all.push(Config.blessLevel.load("blessLevel"));
        all.push(Config.blessType.load("blessType"));
        all.push(Config.bossRush.load("bossRush"));
        all.push(Config.buildingLevel.load("buildingLevel"));
        all.push(Config.caveRush.load("caveRush"));
        all.push(Config.collection.load("collection"));
        all.push(Config.const.load("const"));
        all.push(Config.dwarvenKing.load("dwarvenKing"));
        all.push(Config.enemy.load("enemy"));
        all.push(Config.extraReward.load("extraReward"));
        all.push(Config.gear.load("gear"));
        all.push(Config.gearLevel.load("gearLevel"));
        all.push(Config.goldRush.load("goldRush"));
        all.push(Config.guide.load("guide"));
        all.push(Config.guideText.load("guideText"));
        all.push(Config.hero.load("hero"));
        all.push(Config.heroLevelExp.load("heroLevelExp"));
        all.push(Config.legionHero.load("legionHero"));
        all.push(Config.legionRand.load("legionRand"));
        all.push(Config.legionRush.load("legionRush"));
        all.push(Config.legionWave.load("legionWave"));
        all.push(Config.level.load("level"));
        all.push(Config.mailbox.load("mailbox"));
        all.push(Config.mastery.load("mastery"));
        all.push(Config.mine.load("mine"));
        all.push(Config.mineResearch.load("mineResearch"));
        all.push(Config.mineRewardGear.load("mineRewardGear"));
        all.push(Config.partner.load("partner"));
        all.push(Config.partnerLevel.load("partnerLevel"));
        all.push(Config.pass.load("pass"));
        all.push(Config.plunderHero.load("plunderHero"));
        all.push(Config.plunderLevel.load("plunderLevel"));
        all.push(Config.plunderQuest.load("plunderQuest"));
        all.push(Config.propLevel.load("propLevel"));
        all.push(Config.quest.load("quest"));
        all.push(Config.relic.load("relic"));
        all.push(Config.relicLevel.load("relicLevel"));
        all.push(Config.ring.load("ring"));
        all.push(Config.ringLevel.load("ringLevel"));
        all.push(Config.ringQualityLevel.load("ringQualityLevel"));
        all.push(Config.roulette.load("roulette"));
        all.push(Config.sevenChallenge.load("sevenChallenge"));
        all.push(Config.sevenLogin.load("sevenLogin"));
        all.push(Config.shop.load("shop"));
        all.push(Config.skill.load("skill"));
        all.push(Config.skillLevel.load("skillLevel"));
        all.push(Config.summonExtra.load("summonExtra"));
        all.push(Config.summonWidget.load("summonWidget"));
        all.push(Config.traitComb.load("traitComb"));
        all.push(Config.trait.load("trait"));
        all.push(Config.treasure.load("treasure"));
        all.push(Config.treasureCost.load("treasureCost"));
        all.push(Config.treasureLevel.load("treasureLevel"));
        return Promise.all(all);
    }
}
