export enum SpecialGuideEnum {
    None = 0,
    TouchMine = 202,
    TouchMineItem = 203,
    TouchShopSummonSkill = 302,
    TouchSkillButton = 303,
    CloseSkillView = 304,
    TouchHeroButton = 305,
    TouchUpgradeSkillButton = 306,
    TouchSkillItem = 307,
    TouchEquipSkillButton = 308,
    TouchCloseSkillView = 309,
    TouchAutoSkillButton = 310,
    TouchShopSummonGear = 402,
    TouchGearButton = 403,
    CloseGearView = 404,
    TouchHeroButton2 = 405,
    TouchUpgradeGearButton = 406,
    TouchWeaponView = 407,
    TouchWeaponItem = 408,
    TouchEquipWeaponButton = 409,
    TouchClosEquipWeaponButton = 410,
    TouchArmorView = 411,
    TouchArmorItem = 412,
    TouchEquipArmorButton = 413,
    TouchShopSummonPartner = 502,
    TouchPartnerButton = 503,
    ClosePartnerView = 504,
    TouchUpgradePartnerButton = 505,
    TouchPartnerItem = 506,
    TouchEquipPartnerButton = 507,
    TouchBossButton = 602,
    TouchBattleButton = 701,
    TouchCoinButton = 702,
    TouchTraitToggle = 802,
    TouchChangButton = 803,
    TouchBattleButton2 = 804,
    TouchSnowButton = 805,
    TouchSearchButton = 901,
    TouchUpgradeMineButton = 902,
    TouchHeroButton3 = 1001,
    TouchChangeHero = 1002,
    TouchUpgradeHeroButton = 1003,
    TouchCloseHeroView = 1004,
    TouchMasteryButton = 1005,
    TouchUpgradeMastery = 1006,
    TouchCaveRushButton = 1102,
    TouchCaveRushReward = 1200,
    TouchHeroButton4 = 1201,
    TouchRelicToggle = 1202,
    TouchSearchRelicButton = 1203,
    TouchAnyWhere = 1204,
    TouchRelicIcon = 1205,
    TouchRelicItem = 1206,
    TouchRelicEquipButton = 1207,
    TouchLegionRushButton = 1302,
    TouchLegionRushReward = 1401,
    TouchLegionRushReward2 = 1402,
    TouchHeroButton5 = 1403,
    TouchHeroToggle = 1404,
    TouchRingButton = 1405,
    TouchRingItem = 1406,
    TouchRingEquipButton = 1407,
    TouchMineButton = 1501,
    TouchMineRobButton = 1502,
    TouchFirstBuild = 1503,
    TouchBuildLevelUp = 1504,
    TouchPutHeroButton = 1505,
    TouchRobButton = 1506,
    TouchClosePutView = 1507,
    TouchCloseLevelUpView = 1508,
    TouchBuildReward = 1509,
    TouchGetRobReward = 1510,
    TouchRobLevelButton = 1511,
    TouchCloseRewardButton = 1512,
    TouchAchieveReward = 1513,
    TouchQuitRobView = 1514,
    TouchTreasureButton = 1515,
    TouchTreasure = 1516,
    TouchTreasureItem = 1517,
    TouchBuyTreasure = 1518,
    TouchTreasureEquip = 1519
}
export enum GuideEnums {
    NODE_VISIBLE,
    Task_CAN_FINISH,
    FIRST_DEAD,
    UNLOCK_SYSTEM,
    UNLOCK_CUSTOMS,
    IS_EXIST_ONE_ACTIVE_PRODUCT,
    IS_EXIST_ACTIVE_PRODUCT,
    IS_EXIST_BLANK_COORDINATE,
    IS_EXIST_ONE_ACTIVE_CREATOR_COORDINATE,
    IS_PLAYER_CAN_LEVEL_UP
}
export enum GuideVerifactionType {
    CLICK_IN_REGIN,
    DRAG_IN_REGIN,
    POP_VIEW_OPEN,
    NET_REQUEST_SUCCESS
}
export enum GuideVerifactionEvent {
    CLICK_IN_REGIN = 'CLICK_IN_REGIN',
    DRAG_IN_REGIN = 'DRAG_IN_REGIN'
}
export enum GuideCommandType {
    CLICK,
    DRAG
}
export enum GuideEvent {
    TASK_VERIFICTION_FAILED = 'GUIDE_EVENT_TASK_VERIFICTION_FAILED',
    TASK_ACTIVE = 'GUIDE_EVENT_TASK_ACTIVE',
    TASK_DEACTIVE = 'GUIDE_EVENT_TASK_DEACTIVE',
    STEP_SUCCESS = 'GUIDE_EVENT_STEP_SUCCESS',
    END = 'GUIDE_EVENT_END',
    COMPLETE_SPECIAL_GUIDE = 'COMPLETE_SPECIAL_GUIDE',
    COMPLETE_NORMAL_GUIDE = 'COMPLETE_NORMAL_GUIDE'
}
