export const enum EVideoType {
    AdShop = "AdShop",
    AdPass = "AdPass",
    AdGear = "AdGear",
    AdSkill = "AdSkill",
    AdPartner = "AdPartner",
    AdQuest = "AdQuest",
    AdSpin = "AdSpin",
    AdGold = "AdGold",
    AdDiamand = "AdDiamand",
    AdBless1 = "AdBless1",
    AdBless2 = "AdBless2",
    AdBless3 = "AdBless3",
    AdObtain = "AdObtain",
    AdBossRush = "AdBossRush",
    AdGoldRush = "AdGoldRush",
    AdDwarvenKing = "AdDwarvenKing",
    AdCaveRush = "AdCaveRush",
    AdLegionRush = "AdLegionRush",
    AdLegionReFresh = "AdLegionReFresh",
    AdMine = "AdMine",
    AdDrill = "AdDrill",
    AdBomb = "AdBomb",
    AdMineResearch = "AdMineResearch",
    Mail = "Mail",
    AdTrait = "AdTrait",
    AdHeroExp = "AdHeroExp",
    AdSpeedUp = "AdSpeedUp",
    Rob = "Plunder",
    AdPlunderSpeedUp = "AdPlunderSpeedUp"
}
export const enum EOpenUIType {
    LevelSuecess = "LevelSuecess",
    LevelFailed = "LevelFailed",
    Shop = "Shop",
    Setting = "Setting",
    Hero = "Hero",
    Partner = "Partner",
    Battle = "Battle",
    Mine = "Mine",
    Collection = "Collection",
    Bless = "Bless",
    DayTask = "DayTask",
    Roulette = "Roulette",
    Pass = "Pass",
    Idle = "Idle",
    Rush = "Rush",
    Rob = "Plunder"
}
export const enum EInsertAdType {
    UICloseAd = "UICloseAd",
    LevelAd = "LevelAd",
    RushAd = "RushAd"
}
